name: Windows - Litemanager
on: workflow_dispatch

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 30  # 防止无限运行

    steps:
    - name: Download and install Essentials
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat" -UseBasicParsing
        cmd /c Downloads.bat

    - name: Run LiteManager
      run: cmd /c show.bat
      
    - name: Time Counter
      run: cmd /c loop.bat
